### ISSUE TITLE
Doesn't work on macOS Sierra

### ISSUE THREAD

**Issue by nehayward** [sindresorhus/icloud-tabs#4]

**Comment by sindresorhus** [comment]
Tests are passing for me on macOS Sierra. You're gonna have to provide some more info if you want me to look into this. Preferably a [failing test](https://github.com/avajs/ava#failing-tests).

**Comment by nehayward** [comment]
Is this not the same issue you have. I couldn't get URLs from your function. https://github.com/josh-/CloudyTabs/issues/33

**Comment by mcdado** [comment]
```
$ node
> const tabs = require('icloud-tabs');
undefined
> tabs.sync()
[ { deviceId: 'WebFeedSubscriptionsKey',
    deviceName: undefined,
    modified: Invalid Date,
    tabs: [] },
  { deviceId: '11111111111-2222-3333-AAAA-BBBBBBBBBBB',
    deviceName: undefined,
    modified: Invalid Date,
    tabs: [] },
  { deviceId: '11111111111-2222-3333-AAAA-BBBBBBBBBBB',
    deviceName: undefined,
    modified: Invalid Date,
    tabs: [] },
  { deviceId: '11111111111-2222-3333-AAAA-BBBBBBBBBBB',
    deviceName: undefined,
    modified: Invalid Date,
    tabs: [] } ]
>
```

I modified the hex `deviceId`s, just to anonymise.

**Comment by lukaskollmer** [comment]
The problem is that, since High Sierra, `~/Library/SyncedPreferences/com.apple.Safari.plist` is encrypted. However, it appears that iCloud tab information can also be loaded from `~/Library/Safari/CloudTabs.db`, which is not encrypted.

(see https://github.com/kmarchand/iCloudTabsAlfredWorkflow for reference, their implementation works fine on High Sierra)

**Comment by sindresorhus** [comment]
That requires full-disk access now, which mean the user has to manually add the Terminal or whatever is used to an allow list. That's just not feasible, so I'm just going to deprecate this package.
